#version: '3.8'
# see here https://docs.docker.com/compose/compose-file/compose-versioning/
services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports: 
      - 6379:6379
    networks:
      - dummynetwork
  
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - dummynetwork

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - be
    networks:
      - dummynetwork

networks:
  dummynetwork:
    driver: bridge
