# Use the official MongoDB image from Docker Hub
FROM redis:latest

# Remember to map external port to the container's 
# port 6379
EXPOSE 6379

# Command to run MongoDB
CMD ["redis-server"]
